package pathstoreweb.pathstoreadminpanel.services;

import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.validation.BindingResult;
import org.springframework.validation.ObjectError;

/**
 * This class is used to format all the errors that could be generated by incorrect user-passed data
 *
 * @see BindingResult#getAllErrors()
 */
public class ErrorFormatter implements IFormatter {

  /** List of errors from {@link BindingResult#getAllErrors()} */
  private final List<ObjectError> objectErrorList;

  /** @param objectErrorList {@link #objectErrorList} */
  public ErrorFormatter(final List<ObjectError> objectErrorList) {
    this.objectErrorList = objectErrorList;
  }

  /** @return json array of all the errors */
  @Override
  public String format() {
    JSONArray array = new JSONArray();

    for (ObjectError error : this.objectErrorList) {
      JSONObject object = new JSONObject();

      object.put("error_status", error.getDefaultMessage());

      array.put(object);
    }

    return array.toString();
  }
}
