package pathstoreweb.pathstoreadminpanel.services;

import org.springframework.http.ResponseEntity;

/** Interface to be implemented in all services. */
public interface IService {
  /**
   * @return json response generated by a service formatter
   * @see IFormatter
   */
  ResponseEntity<String> response();
}
