package pathstoreweb.pathstoreadminpanel.services;

/** Interface to be implemented in all services. */
public interface IService {
  /**
   * @return json response generated by a service formatter
   * @see pathstoreweb.pathstoreadminpanel.formatter.IFormatter
   */
  String response();
}
