package pathstoreweb.pathstoreadminpanel.services;

import org.json.JSONArray;
import org.json.JSONObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import pathstoreweb.pathstoreadminpanel.validator.ValidatedPayload;

import java.util.Arrays;
import java.util.Objects;

/**
 * This class is used to format all the errors that could be generated by incorrect user-passed data
 */
public class ValidityErrorFormatter implements IFormatter {

  /** List of errors gather from {@link ValidatedPayload#getErrors()} */
  private final String[] objectErrorList;

  /** @param objectErrorList {@link #objectErrorList} */
  public ValidityErrorFormatter(final String[] objectErrorList) {
    this.objectErrorList = objectErrorList;
  }

  /** @return json array of all the errors */
  @Override
  public ResponseEntity<String> format() {
    JSONArray array = new JSONArray();

    Arrays.stream(this.objectErrorList)
        .filter(Objects::nonNull)
        .forEach(i -> array.put(new JSONObject().put("error", i)));

    return new ResponseEntity<>(array.toString(), HttpStatus.BAD_REQUEST);
  }
}
